### ISSUE TITLE
lilyurl1.5.tcl and lilyurl1.2.tcl: cloudflare SSL error: tlsv1 alert internal error

### ISSUE THREAD

**Issue by YogSottot** [starlilyth/IRC-Eggdrop-TCL#4]
dev-lang/tcl-8.6.6
dev-tcltk/tcllib-1.15-r2
dev-tcltk/tls-1.6.7
net-irc/eggdrop-1.8.0

When try link from the  https://centmin.sh/ 
```
SSL channel "sock18863d0": error: tlsv1 alert internal error
SSL channel "sock18961e0": error: tlsv1 alert internal error
SSL channel "sock18174e0": error: tlsv1 alert internal error
```
https://rust-lang.org/
```
SSL channel "sock1794940": error: sslv3 alert handshake failure
```

**Comment by starlilyth** [comment]
Developed for Eggdrop 1.6. Completely untested with Eggdrop 1.8.

**Comment by YogSottot** [comment]
I compiled eggdrop-1.6.20 on gentoo
dev-lang/tcl-8.6.6
dev-tcltk/tcllib-1.15-r2
dev-tcltk/tls-1.6.7

Also I compiled eggdrop-1.6.21 and 1.6.20 on debian 
tcl 8.6.0+8
tcl-tls 1.6+dfsg-3:
tcllib 1.16-dfsg-2:
libsqlite3-tcl 3.8.7.1-1+deb8u2

The errors absolutely the same.
```
SSL channel "sock19d9620": error: sslv3 alert handshake failure
SSL channel "sock1a0fe60": error: tlsv1 alert internal error

```

This is only with sites with cloudflare SSL, other https links works ok.

**Comment by starlilyth** [comment]
Sounds like a problem with your CA bundle, I would make sure your servers certs are up to date. 
Since it only happens with cloudflare, its clearly not a problem with the bot code.

**Comment by c0t0d0s2** [comment]
My guess is that this is an SSL/TLS issue with cloudflare and your setup.
I have no idea how starlilyth's code could be at fault here

**Comment by YogSottot** [comment]
> its clearly not a problem with the bot code.
Yes, it is a problem with a script code. But if find the solution in a wiki https://wiki.tcl.tk/2630 «Using TLS in 2015 »
CloudFlare Universal SSL uses certificates that have multiple domains in the one certificate. 
https://dropbear.xyz/2015/06/08/checking-cloudflare-ssl/
The way that the client tells the server which website it is looking for is Server Name Indication (SNI). As part of the TLS handshaking the client tells the server “I want website www.enc.com.au”.

In tcl-tls you should use -servername option that enabled SNI. (for tcl-tls 1.6.x). In 1.7.11 added the new option  -autoservername.
I'm use dev-tcltk/tls-1.6.7 so for me solution is:
```
    proc tls:socket args {
        set opts [lrange $args 0 end-2]
        set host [lindex $args end-1]
        set port [lindex $args end]
        ::tls::socket -ssl3 false -ssl2 false -tls1 true -servername $host {*}$opts $host $port
    }

    ::http::register https 443 tls:socket
```
The problem is gone, eggdrop-1.8.0 stable release works ok.

**Comment by starlilyth** [comment]
Excellent work, thank you! Yes there will need to be some version detection, or I may just make a new version for newer libs.

**Comment by YogSottot** [comment]
There is code example with solution with detection of version tcl-tls  https://github.com/teeli/urltitle/commit/f063062686020e40ba6ff0f2c576d4d5f5686bd8
